services:
  namenode:
    image: apache/hadoop:3.4.1
    hostname: namenode
    command: [hdfs, namenode]
    ports:
      - 8020:8020
      - 9870:9870
    env_file:
      - ./hadoop/config
    environment:
      ENSURE_NAMENODE_DIR: /opt/hadoop/srv/hdfs/name
  datanode:
    image: apache/hadoop:3.4.1
    command: [hdfs, datanode]
    env_file:
      - ./hadoop/config
  resourcemanager:
    image: apache/hadoop:3.4.1
    hostname: resourcemanager
    command: [yarn, resourcemanager]
    ports:
      - 8088:8088
    env_file:
      - ./hadoop/config
    volumes:
      - ./hadoop/test.sh:/opt/test.sh
  nodemanager:
    image: apache/hadoop:3.4.1
    command: [yarn, nodemanager]
    ports:
      - 8042:8042
    env_file:
      - ./hadoop/config
