name: Release

on:
  release:
    types: published

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout Repositry
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Set up Scala Cache
        uses: coursier/cache-action@v6

      - name: Set up Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:8
          apps: scala:3.7.2

      - name: Check Code Formatting
        run: just check-formatting

      - name: Compile
        run: just compile

      - name: Test
        run: just test

      - name: Package Library
        run: just package
      
      - name: Package Assembly
        run: just package-assembly

      - name: Upload Library Package
        uses: actions/upload-artifact@v4
        with:
          name: Library Package
          path: ./dist/polygon-overlay-hadoop-mapreduce-naive.jar
          retention-days: 7

      - name: Upload Assembly Package
        uses: actions/upload-artifact@v4
        with:
          name: Assembly Package
          path: ./dist/polygon-overlay-hadoop-mapreduce-naive-all.jar
          retention-days: 7

  upload-release-assets:
    name: Upload Release Assets
    needs: package-application
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Library Package
        uses: actions/download-artifact@v4
        with:
          name: Library Package

      - name: Download Assembly Package
        uses: actions/download-artifact@v4
        with:
          name: Assembly Package

      - name: Upload Library Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: polygon-overlay-hadoop-mapreduce-naive.jar
          asset_name: polygon-overlay-hadoop-mapreduce-naive.jar
          asset_content_type: application/java-archive

      - name: Upload Assembly Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: polygon-overlay-hadoop-mapreduce-naive-all.jar
          asset_name: polygon-overlay-hadoop-mapreduce-naive-all.jar
          asset_content_type: application/java-archive
